# Generated by Django 3.2.9 on 2022-02-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromMail', models.EmailField(max_length=254)),
                ('ToMail', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
