# Generated by Django 3.2.9 on 2022-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0003_alter_usermail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermail',
            name='Date',
            field=models.TimeField(),
        ),
    ]
